<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="DigiBankSG_Login" time="154" tests="0" failures="2" errors="0">
   <testsuite name="DigiBankSG_Login" tests="0" failures="2" errors="0" time="154" timestamp="2018-06-01 10:52:06" hostname="SRAVANIBHARAT - DESKTOP-7OG2TPC" id="Test Suites/Mobile/DigiBankSG_Login">
      <properties>
         <property name="deviceName" value="emulator-5554 (Android SDK built for x86 - Android 8.1.0)"/>
         <property name="devicePlatform" value=""/>
         <property name="logFolder" value="G:\\Katalon Projects\\DigiBank_Demo\\Reports\\Mobile\\DigiBankSG_Login\\20180601_105201"/>
         <property name="logFiles" value="G:\\Katalon Projects\\DigiBank_Demo\\Reports\\Mobile\\DigiBankSG_Login\\20180601_105201\\appium.log, G:\\Katalon Projects\\DigiBank_Demo\\Reports\\Mobile\\DigiBankSG_Login\\20180601_105201\\execution0.log"/>
         <property name="attachments" value="G:\\Katalon Projects\\DigiBank_Demo\\Reports\\Mobile\\DigiBankSG_Login\\20180601_105201\\1527830675436.png, G:\\Katalon Projects\\DigiBank_Demo\\Reports\\Mobile\\DigiBankSG_Login\\20180601_105201\\1527830676841.png"/>
         <property name="hostName" value="SRAVANIBHARAT - DESKTOP-7OG2TPC"/>
         <property name="os" value="Windows 10 64bit"/>
         <property name="katalonVersion" value="5.4.1.1"/>
         <property name="deviceOS" value="Android"/>
         <property name="appiumVersion" value="1.8.0"/>
         <property name="deviceModel" value="Android SDK built for x86"/>
         <property name="hostAddress" value="192.168.43.119"/>
         <property name="deviceManufacturer" value="Google"/>
         <property name="deviceId" value="emulator-5554"/>
         <property name="deviceName" value="emulator-5554 (Android SDK built for x86 - Android 8.1.0)"/>
         <property name="deviceOSVersion" value="8.1.0"/>
      </properties>
      <testcase name="Test Cases/Mobile/DigibankSG_Login_Module/DigiBankSG_Login_TC001_BlankUserName_ErrorValidation" classname="Test Cases/Mobile/DigibankSG_Login_Module/DigiBankSG_Login_TC001_BlankUserName_ErrorValidation" status="FAILED">
         <failure type="FAILED" message="Unable to start app at: 'G:\APK Files\DBS digibank SG_v2.0.002_apkpure.com.apk' (Root cause: com.kms.katalon.core.appium.exception.AppiumStartException: Fail to start Appium server in 30 seconds)"/>
         <system-out><![CDATA[2018-06-01 10:52:07 - [TEST_CASE][FAILED] - Test Cases/Mobile/DigibankSG_Login_Module/DigiBankSG_Login_TC001_BlankUserName_ErrorValidation: Test Cases/Mobile/DigibankSG_Login_Module/DigiBankSG_Login_TC001_BlankUserName_ErrorValidation FAILED because (of) Unable to start app at: 'G:\APK Files\DBS digibank SG_v2.0.002_apkpure.com.apk' (Root cause: com.kms.katalon.core.appium.exception.AppiumStartException: Fail to start Appium server in 30 seconds)

2018-06-01 10:52:08 - [TEST_STEP][FAILED] - startApplication: Unable to start app at: 'G:\APK Files\DBS digibank SG_v2.0.002_apkpure.com.apk' (Root cause: com.kms.katalon.core.appium.exception.AppiumStartException: Fail to start Appium server in 30 seconds)

2018-06-01 10:52:41 - [MESSAGE][FAILED] - Unable to start app at: 'G:\APK Files\DBS digibank SG_v2.0.002_apkpure.com.apk' (Root cause: com.kms.katalon.core.appium.exception.AppiumStartException: Fail to start Appium server in 30 seconds)]]></system-out>
         <system-err><![CDATA[2018-06-01 10:52:07 - [TEST_CASE][FAILED] - Test Cases/Mobile/DigibankSG_Login_Module/DigiBankSG_Login_TC001_BlankUserName_ErrorValidation: Test Cases/Mobile/DigibankSG_Login_Module/DigiBankSG_Login_TC001_BlankUserName_ErrorValidation FAILED because (of) Unable to start app at: 'G:\APK Files\DBS digibank SG_v2.0.002_apkpure.com.apk' (Root cause: com.kms.katalon.core.appium.exception.AppiumStartException: Fail to start Appium server in 30 seconds)]]></system-err>
      </testcase>
      <testcase name="Test Cases/Mobile/DigibankSG_Login_Module/DigiBankSG_Login_TC001_BlankUserName_ErrorValidation_Fail" classname="Test Cases/Mobile/DigibankSG_Login_Module/DigiBankSG_Login_TC001_BlankUserName_ErrorValidation_Fail" status="FAILED">
         <failure type="FAILED" message="Unable to verify if object 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtview_InvalidLoginDetails' has attribute 'text' with value 'Sorry, you have entered an valid User ID. Please try again.' (Root cause: Object 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtview_InvalidLoginDetails' has attribute 'text' with actual value 'Sorry, you have entered an invalid User ID. Please try again.' instead of expected value 'Sorry, you have entered an valid User ID. Please try again.')"/>
         <system-out><![CDATA[2018-06-01 10:52:41 - [TEST_CASE][FAILED] - Test Cases/Mobile/DigibankSG_Login_Module/DigiBankSG_Login_TC001_BlankUserName_ErrorValidation_Fail: Test Cases/Mobile/DigibankSG_Login_Module/DigiBankSG_Login_TC001_BlankUserName_ErrorValidation_Fail FAILED because (of) Unable to verify if object 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtview_InvalidLoginDetails' has attribute 'text' with value 'Sorry, you have entered an valid User ID. Please try again.' (Root cause: Object 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtview_InvalidLoginDetails' has attribute 'text' with actual value 'Sorry, you have entered an invalid User ID. Please try again.' instead of expected value 'Sorry, you have entered an valid User ID. Please try again.')

2018-06-01 10:52:41 - [TEST_STEP][PASSED] - startApplication: Started app at: 'G:\APK Files\DBS digibank SG_v2.0.002_apkpure.com.apk'

2018-06-01 10:53:48 - [MESSAGE][PASSED] - Started app at: 'G:\APK Files\DBS digibank SG_v2.0.002_apkpure.com.apk'

2018-06-01 10:53:48 - [TEST_STEP][PASSED] - tap: Tapped on element 'Object Repository/Mobile/DigiBankSG_Landing_OR/LandingPageFirstTimeUse_btn_SeeWhatsNew'

2018-06-01 10:53:54 - [MESSAGE][PASSED] - Tapped on element 'Object Repository/Mobile/DigiBankSG_Landing_OR/LandingPageFirstTimeUse_btn_SeeWhatsNew'

2018-06-01 10:53:54 - [TEST_STEP][PASSED] - delay: Delayed 5 second(s)

2018-06-01 10:53:59 - [MESSAGE][PASSED] - Delayed 5 second(s)

2018-06-01 10:53:59 - [TEST_STEP][PASSED] - tap: Tapped on element 'Object Repository/Mobile/DigiBankSG_Landing_OR/LandingPageFirstTimeUse_img_View5'

2018-06-01 10:54:01 - [MESSAGE][PASSED] - Tapped on element 'Object Repository/Mobile/DigiBankSG_Landing_OR/LandingPageFirstTimeUse_img_View5'

2018-06-01 10:54:01 - [TEST_STEP][PASSED] - delay: Delayed 5 second(s)

2018-06-01 10:54:06 - [MESSAGE][PASSED] - Delayed 5 second(s)

2018-06-01 10:54:06 - [TEST_STEP][PASSED] - tap: Tapped on element 'Object Repository/Mobile/DigiBankSG_Landing_OR/LandingPageFirstTimeUse_txtview_StartNow'

2018-06-01 10:54:07 - [MESSAGE][PASSED] - Tapped on element 'Object Repository/Mobile/DigiBankSG_Landing_OR/LandingPageFirstTimeUse_txtview_StartNow'

2018-06-01 10:54:07 - [TEST_STEP][PASSED] - tap: Tapped on element 'Object Repository/Mobile/DigiBankSG_Landing_OR/LandingPage_txtview_Login'

2018-06-01 10:54:23 - [MESSAGE][PASSED] - Tapped on element 'Object Repository/Mobile/DigiBankSG_Landing_OR/LandingPage_txtview_Login'

2018-06-01 10:54:23 - [TEST_STEP][PASSED] - tap: Tapped on element 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtedit_UserID'

2018-06-01 10:54:25 - [MESSAGE][PASSED] - Tapped on element 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtedit_UserID'

2018-06-01 10:54:25 - [TEST_STEP][PASSED] - setText: Text '' has been set to element 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtedit_UserID'

2018-06-01 10:54:25 - [MESSAGE][WARNING] - Timeout '0' is invalid. Using default page load timeout: '30'

2018-06-01 10:54:27 - [MESSAGE][PASSED] - Text '' has been set to element 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtedit_UserID'

2018-06-01 10:54:27 - [TEST_STEP][PASSED] - hideKeyboard: Keyboard is hidden

2018-06-01 10:54:29 - [MESSAGE][PASSED] - Keyboard is hidden

2018-06-01 10:54:29 - [TEST_STEP][PASSED] - tap: Tapped on element 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtedit_PIN'

2018-06-01 10:54:29 - [MESSAGE][WARNING] - Timeout '0' is invalid. Using default page load timeout: '30'

2018-06-01 10:54:31 - [MESSAGE][PASSED] - Tapped on element 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtedit_PIN'

2018-06-01 10:54:31 - [TEST_STEP][PASSED] - setText: Text '123456' has been set to element 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtedit_PIN'

2018-06-01 10:54:31 - [MESSAGE][WARNING] - Timeout '0' is invalid. Using default page load timeout: '30'

2018-06-01 10:54:32 - [MESSAGE][PASSED] - Text '123456' has been set to element 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtedit_PIN'

2018-06-01 10:54:32 - [TEST_STEP][PASSED] - hideKeyboard: Keyboard is hidden

2018-06-01 10:54:33 - [MESSAGE][PASSED] - Keyboard is hidden

2018-06-01 10:54:33 - [TEST_STEP][PASSED] - tap: Tapped on element 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_button_Login'

2018-06-01 10:54:33 - [MESSAGE][WARNING] - Timeout '0' is invalid. Using default page load timeout: '30'

2018-06-01 10:54:34 - [MESSAGE][PASSED] - Tapped on element 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_button_Login'

2018-06-01 10:54:34 - [TEST_STEP][FAILED] - verifyElementAttributeValue: Unable to verify if object 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtview_InvalidLoginDetails' has attribute 'text' with value 'Sorry, you have entered an valid User ID. Please try again.' (Root cause: Object 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtview_InvalidLoginDetails' has attribute 'text' with actual value 'Sorry, you have entered an invalid User ID. Please try again.' instead of expected value 'Sorry, you have entered an valid User ID. Please try again.')

2018-06-01 10:54:34 - [MESSAGE][WARNING] - Timeout '0' is invalid. Using default page load timeout: '30'

2018-06-01 10:54:36 - [MESSAGE][FAILED] - Object 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtview_InvalidLoginDetails' has attribute 'text' with actual value 'Sorry, you have entered an invalid User ID. Please try again.' instead of expected value 'Sorry, you have entered an valid User ID. Please try again.'
[[ATTACHMENT|G:\\Katalon Projects\\DigiBank_Demo\\Reports\\Mobile\\DigiBankSG_Login\\20180601_105201\\1527830675436.png]]

2018-06-01 10:54:37 - [MESSAGE][FAILED] - Unable to verify if object 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtview_InvalidLoginDetails' has attribute 'text' with value 'Sorry, you have entered an valid User ID. Please try again.' (Root cause: Object 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtview_InvalidLoginDetails' has attribute 'text' with actual value 'Sorry, you have entered an invalid User ID. Please try again.' instead of expected value 'Sorry, you have entered an valid User ID. Please try again.')
[[ATTACHMENT|G:\\Katalon Projects\\DigiBank_Demo\\Reports\\Mobile\\DigiBankSG_Login\\20180601_105201\\1527830676841.png]]]]></system-out>
         <system-err><![CDATA[2018-06-01 10:52:41 - [TEST_CASE][FAILED] - Test Cases/Mobile/DigibankSG_Login_Module/DigiBankSG_Login_TC001_BlankUserName_ErrorValidation_Fail: Test Cases/Mobile/DigibankSG_Login_Module/DigiBankSG_Login_TC001_BlankUserName_ErrorValidation_Fail FAILED because (of) Unable to verify if object 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtview_InvalidLoginDetails' has attribute 'text' with value 'Sorry, you have entered an valid User ID. Please try again.' (Root cause: Object 'Object Repository/Mobile/DigiBankSG_Login_OR/LoginPage_txtview_InvalidLoginDetails' has attribute 'text' with actual value 'Sorry, you have entered an invalid User ID. Please try again.' instead of expected value 'Sorry, you have entered an valid User ID. Please try again.')]]></system-err>
      </testcase>
      <system-out><![CDATA[2018-06-01 10:52:06 - [TEST_SUITE][FAILED] - DigiBankSG_Login: Test Cases/Mobile/DigibankSG_Login_Module/DigiBankSG_Login_TC001_BlankUserName_ErrorValidation FAILED because (of) Unable to start app at: 'G:\APK Files\DBS digibank SG_v2.0.002_apkpure.com.apk' (Root cause: com.kms.katalon.core.appium.exception.AppiumStartException: Fail to start Appium server in 30 seconds)]]></system-out>
      <system-err><![CDATA[2018-06-01 10:52:06 - [TEST_SUITE][FAILED] - DigiBankSG_Login: Test Cases/Mobile/DigibankSG_Login_Module/DigiBankSG_Login_TC001_BlankUserName_ErrorValidation FAILED because (of) Unable to start app at: 'G:\APK Files\DBS digibank SG_v2.0.002_apkpure.com.apk' (Root cause: com.kms.katalon.core.appium.exception.AppiumStartException: Fail to start Appium server in 30 seconds)]]></system-err>
   </testsuite>
</testsuites>
